### ISSUE TITLE
Library icon conflicts with application icon

### ISSUE THREAD

**Issue by gabosvk** [vignesh-iopex/confirmdialog#3]
Hi,

I'm getting following error during building my app:

Error:(17, 3) Execution failed for task ':GroupinApp:processDemoDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:17:3
  	is also present at com.github.vignesh-iopex:confirmdialog:1.0:13:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:14:2 to override

Also tried to add tools:replace"android:icon" which worked but suddenly my custom theme was ignored and couldn't make it work again.

Could you please remove unnecessary attributes from your AndroidManifes.xml file? There is no need for having android:allowBackup="true", android:label="@string/app_name", android:icon="@drawable/ic_launcher" in library projects.

That would really help me because I love your dialog and so want to use it.

Thanks.

Gabriel.

**Comment by vignesh-iopex** [comment]
published a release v-1.0.1 with the fix. will be available soon in maven central

**Comment by gabosvk** [comment]
Thank you very much. Really appreciate it!
